### ISSUE TITLE
Button to start new game at life overview screen

### ISSUE THREAD

**Issue by KoenArends** [Alwindh/MagiCounter#27]
When a game has start, there is no way to go back to the deck selection screen. 
Create a button at the game screen to restart.

A alert with a question like: "would you like to start a new game" should pop up.
The game data should not be recorded.

**Comment by Alwindh** [comment]
![Capture](https://user-images.githubusercontent.com/42200913/74771698-e8a23680-528e-11ea-9409-c879f555db1d.PNG)

Like this?
